FROM openjdk:17-jdk-alpine

COPY target/cameriere-config-server-0.0.1-SNAPSHOT.jar cameriere-config-server-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "cameriere-config-server-0.0.1-SNAPSHOT.jar"]
