services:
  network-deploy-service:
    networks:
      - cameriere-network

  microservice-base-configs:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"

  microservice-config-server-configs:
    extends:
      service: microservice-base-configs
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888