services:
  menudb:
    container_name: menudb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: menudb
    extends:
      file: common-configs.yml
      service: microservice-db-configs

  ordersdb:
    container_name: ordersdb
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ordersdb
    extends:
      file: common-configs.yml
      service: microservice-db-configs

  rabbit:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-configs.yml
      service: network-deploy-service

  config-server:
    image: "lucasfacci/config-server:0.0.2"
    container_name: config-server-ms
    ports:
      - "8888:8888"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-configs.yml
      service: microservice-base-configs

  eureka:
    image: "lucasfacci/eureka:0.0.1"
    container_name: eureka-ms
    ports:
      - "8761:8761"
    environment:
      SPRING_APPLICATION_NAME: "eureka"
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-configs.yml
      service: microservice-config-server-configs

  menu:
    image: "lucasfacci/menu:0.0.5"
    container_name: menu-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "menu"
      SPRING_DATASOURCE_URL: "jdbc:mysql://menudb:3306/menudb"
    depends_on:
      menudb:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-configs.yml
      service: microservice-eureka-configs

  order:
    image: "lucasfacci/order:0.0.6"
    container_name: order-ms
    ports:
      - "8081:8081"
    environment:
      SPRING_APPLICATION_NAME: "order"
      SPRING_DATASOURCE_URL: "jdbc:mysql://ordersdb:3306/ordersdb"
    depends_on:
      ordersdb:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-configs.yml
      service: microservice-eureka-configs

  gateway:
    image: "lucasfacci/gateway:0.0.1"
    container_name: gateway-ms
    ports:
      - "7000:7000"
    environment:
      SPRING_APPLICATION_NAME: "gateway"
    depends_on:
      menu:
        condition: service_healthy
      order:
        condition: service_healthy
    extends:
      file: common-configs.yml
      service: microservice-eureka-configs

networks:
  cameriere-network:
    driver: "bridge"